/**
 *    Copyright 2026 Cutout Studios LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  createObject,
  createPaintMaterialWithPalette as paint,
  XYZ,
} from "~/3D";
import { length, max, min, round } from "~/alias";
import { doTimes, flat, interpolate, repeat } from "~/common";

const PORTRAIT_OFFSET = 81,
  PORTRAIT_HALF_HEIGHT = 0.15,
  PORTRAIT_SCALE = PORTRAIT_HALF_HEIGHT / 20,
  PORTRAIT_POSITION = [0, 0, 1.2] as XYZ,
  // generated by scripts/encodePortrait.ts
  PORTRAIT_DATA =
    `CZ_Zd^CZd^ZaCZZaPkCZPkDeGJ-C0:DePkHq@lHqBwZad^PkGJCZ6NGJ6N-C@6C-T3@6T3R;R;T3u4R;u4r;;tBw6~Pkd^g_Pkg__gPk_gWjg_d^_ZGJUG_ZCZGJ_ZR;r;gRDeHq@l@lBw;tWj_g]rGJ0:@6gRg__ZUGgR_ZGJ@6R;R;gRUGGJR;UG0:$1$#$#C-@6~#y=u4~#u4T3$#@#C-0:$#@6~#~:y=@#~#T3C-@#T3`,
  _hsl = (h: number, s: number, l: number) => {
    const a = (s / 100) * min(l / 100, 1 - l / 100),
      f = (n: number) => {
        const k = (n + h / 30) % 12,
          color = l / 100 - a * max(min(k - 3, 9 - k, 1), -1);

        return round(255 * color);
      };

    return (f(0) << 16) | (f(8) << 8) | f(4);
  };

export const portrait = (progress: number) =>
  createObject(
    [PORTRAIT_POSITION],
    [
      0,
      doTimes(length(PORTRAIT_DATA) / 2, (index: number) => [
        (PORTRAIT_DATA.charCodeAt(index * 2) - PORTRAIT_OFFSET) *
        PORTRAIT_SCALE,
        (PORTRAIT_DATA.charCodeAt(index * 2 + 1) - PORTRAIT_OFFSET) *
        PORTRAIT_SCALE,
        -2,
      ]),
    ],
    paint(
      ...flat(
        repeat(5, _hsl(270, interpolate([0, 20], progress), 8)),
        repeat(9, _hsl(220, interpolate([0, 60], progress), 93)),
        repeat(8, _hsl(265, interpolate([0, 18], progress), 63)),
        repeat(9, _hsl(270, interpolate([0, 12], progress), 45)),
        repeat(4, _hsl(217, interpolate([0, 27], progress), 65)),
        repeat(5, _hsl(217, interpolate([0, 18], progress), 43)),
      ),
    ),
  );
