/**
 *    Copyright 2026 Cutout Studios LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  createObject,
  createPaintMaterialWithPalette as paint,
  toRGB,
  XYZ,
} from "~/3D";
import { length } from "~/alias";
import { doTimes, flat, interpolate, repeat } from "~/common";

import GameOptions from "../game/options/module.ts";

const PORTRAIT_OFFSET = 81,
  PORTRAIT_HALF_HEIGHT = 0.15,
  PORTRAIT_SCALE = PORTRAIT_HALF_HEIGHT / 20,
  PORTRAIT_POSITION = [0, 0, 1.2] as XYZ,
  PORTRAIT_DATA = // generated by scripts/encodePortrait.ts
    "Rc`]QgK`>YPRK`PRR]K`Db>YRcR]`]RcK`R]`]U[ZP{-t##{-R't#R'R#t#R'?)R#R#?)=#/.=#?)/.##=#U[PRZPR]U[`]6;)O+A9m:t6{)O6;;I;I6;E@PRU[R]?)R'S8S8R'{-S8{-u4;IBM)OBM6U)O>m:t9m9m@j>mQg`]l\\Qgl\\ieQgie]iE@WCZPBME@PRC;/.?)6UBM>YPR>YBMC;?)S8VkLkQgVkQg]iQgK`RcLkLgQgLkIgLg;IE@BMQgRc`]S8n>jM;f@j9mDb@j;f]iiennjMl\\ZPWCjMZPS8jMWCE@S8WCYsLkVkl\\`]ZP@jDbK`@jK`IgQgLgK`IgK`Lgn>S8u4PRE@ZPS8E@C;\\nVk]iodiel\\l\\jMpUpHjMn>n>u4u;{3u4{-", // 402 chars
  PORTRAIT_POINTS = doTimes(length(PORTRAIT_DATA) / 2, (index: number) => [
    (PORTRAIT_DATA.charCodeAt(index * 2) - PORTRAIT_OFFSET) *
    PORTRAIT_SCALE,
    (PORTRAIT_DATA.charCodeAt(index * 2 + 1) - PORTRAIT_OFFSET) *
    PORTRAIT_SCALE,
    -2,
  ]) as XYZ[];

export const portrait = (collected: Set<number>) => {
  const progress = collected.size / 6;

  return createObject(
    [PORTRAIT_POSITION],
    [0, PORTRAIT_POINTS],
    paint(
      ...flat(
        repeat(15, toRGB(270, interpolate([0, 20], progress), 8)),
        repeat(6, toRGB(184, interpolate([0, 40], progress), 95)),
        repeat(23, toRGB(198, interpolate([0, 52], progress), 75)),
        repeat(17, toRGB(219, interpolate([0, 50], progress), 69)),
        doTimes(
          6,
          (index: number) =>
            collected.has(index) ? GameOptions[index][1] : 0x000000FF,
        ),
      ),
    ),
  );
};
