/**
 *    Copyright 2026 Cutout Studios LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  createObject,
  createPaintMaterialWithPalette as paint,
  toRGB,
  XYZ,
} from "~/3D";
import { length } from "~/alias";
import { doTimes, flat, interpolate, repeat } from "~/common";

const PORTRAIT_OFFSET = 81,
  PORTRAIT_HALF_HEIGHT = 0.15,
  PORTRAIT_SCALE = PORTRAIT_HALF_HEIGHT / 20,
  PORTRAIT_POSITION = [0, 0, 1.2] as XYZ,
  // generated by scripts/encodePortrait.ts
  PORTRAIT_DATA =
    "Wb`YRWUd`aSg`aWbUdMaRWE\\MaWbRWMaHbE\\Ud`aWb;@1P1CE4T3R;R;T3{6R;{6r;>nBv;|1PFF;@FFFR1PFR1P>WCpBv>n>nFiCpSg`ai_Sgi_geSggeZiFFWF`YFRFFRWR;r;gPFF59E4>WE\\FRRWFRE\\FFE4R;WjSgPjWjZiSgSg`aUdSgUdMaPjSgOgPjOgMg@dFi>nHbFi@dZigegogPi_`YWFgP`YR;gPWFFFR;WFRoWjPji_`Y`aRW`YFFFiMaHbFiMaMgSgOgMaMgOgMaE4C-T359$1$#$#C-E4~#{6T3UdWbMa`a`YWb$#@#C-59$#E4@#~#T3C-@#T3";
export const portrait = (progress: number) =>
  createObject(
    [PORTRAIT_POSITION],
    [
      0,
      doTimes(length(PORTRAIT_DATA) / 2, (index: number) => [
        (PORTRAIT_DATA.charCodeAt(index * 2) - PORTRAIT_OFFSET) *
        PORTRAIT_SCALE,
        (PORTRAIT_DATA.charCodeAt(index * 2 + 1) - PORTRAIT_OFFSET) *
        PORTRAIT_SCALE,
        -2,
      ]),
    ],
    paint(
      ...flat(
        repeat(7, toRGB(270, interpolate([0, 20], progress), 8)),
        repeat(6, toRGB(220, interpolate([0, 60], progress), 93)),
        repeat(20, toRGB(265, interpolate([0, 18], progress), 63)),
        repeat(14, toRGB(270, interpolate([0, 12], progress), 45)),
        repeat(5, toRGB(217, interpolate([0, 27], progress), 65)),
        repeat(5, toRGB(217, interpolate([0, 18], progress), 43)),
      ),
    ),
  );
