import { FLOAT_32_BYTES } from "~common";

export const PROJECTIVE_TRANSFORM_WIDTH = 4;
export const PROJECTIVE_TRANSFORM_SIZE = PROJECTIVE_TRANSFORM_WIDTH ** 2;
export const PROJECTIVE_TRANSFORM_BYTES = PROJECTIVE_TRANSFORM_SIZE *
  FLOAT_32_BYTES;

export const IS_PROJECTIVE_TRANSFORM_DIRECTION = 0;
export const IS_PROJECTIVE_TRANSFORM_POINT = 1;

export const DEFAULT_PERSPECTIVE_SAFETY_CROP = 0.1;
