/**
 *    Copyright 2026 Cutout Studios LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { createPaintMaterialWithPalette as paint, XOObject, XYZ } from "~/3D";
import { doTimes, repeat } from "~/common";

const PORTRAIT_OFFSET = 81,
  PORTRAIT_HALF_HEIGHT = 0.15,
  PORTRAIT_SCALE = PORTRAIT_HALF_HEIGHT / 20,
  PORTRAIT_POSITION = [0, 0, 1.2] as XYZ,
  // generated by scripts/encodePortrait.ts
  PORTRAIT_DATA =
    `CZ_Zd^CZd^ZaCZZaPkCZPkDeGJ-C0:DePkHq@lHqBwZad^PkGJCZ6NGJ6N-C@6C-T3@6T3R;R;T3u4R;u4r;;tBw6~Pkd^g_Pkg__gPk_gWjg_d^_ZGJUG_ZCZGJ_ZR;r;gRDeHq@l@lBw;tWj_g]rGJ0:@6gRg__ZUGgR_ZGJ@6R;R;gRUGGJR;UG0:$1$#$#C-@6~#y=u4~#u4T3$#@#C-0:$#@6~#~:y=@#~#T3C-@#T3`;

export const portrait = new XOObject(
  doTimes(PORTRAIT_DATA.length / 2, (index) => [
    (PORTRAIT_DATA.charCodeAt(index * 2) - PORTRAIT_OFFSET) * PORTRAIT_SCALE,
    (PORTRAIT_DATA.charCodeAt(index * 2 + 1) - PORTRAIT_OFFSET) *
    PORTRAIT_SCALE,
    -2,
  ]),
  PORTRAIT_POSITION,
  undefined,
  paint(
    repeat(5, 0x121018),
    repeat(9, 0xE6E9F2),
    repeat(8, 0x9C93B0),
    repeat(9, 0x6E6480),
    repeat(4, 0x8FA0BC),
    repeat(5, 0x5A6880),
  ),
);
